#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/pipeline.env"
[ -f "$ENV_FILE" ] || ENV_FILE="$SCRIPT_DIR/pipeline.env.example"
set -a
source "$ENV_FILE"
set +a

QT_QPA_PLATFORM="$QT_QPA_PLATFORM" \
PROJECTNAME="$PROJECTNAME" \
PROJECTSROOT="$PROJECTSROOT" \
PXR_PLUGINPATH_NAME="$PXR_PLUGINPATH_NAME_USDVIEW" \
"$USDVIEW_LAUNCHER"
